name: Package and deploy Labspace

env:
  DOCKERHUB_REPO: ghcr.io/${{ github.repository_owner }}/labspace-dhi-launch

permissions:
  contents: read

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push-labspace:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Labspace
        uses: dockersamples/publish-labspace-action@v2
        with:
          target_repo: ${{ env.DOCKERHUB_REPO }}
  build-and-push-initial-container:
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      id-token: write
      packages: write
    with:
      output: image
      push: true
      platforms: linux/amd64,linux/arm64
      sbom: true
      cache: true
      sign: false
      context: project/
      meta-images: |
        ghcr.io/${{ github.repository_owner }}/dinner
      meta-tags: |
        initial
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
